---
  name: test-non-destructive
  on:
    pull_request:
      types: ['opened', 'reopened', 'synchronize']
    merge_group:
    workflow_dispatch:
  
  jobs:
    test-non-destructive:
      uses: kewalaka/terraform-azurerm-avm-template/.github/workflows/test-non-destructive-template.yml@feat/test-non-destructive
      name: test changes are non-destructive
      secrets: inherit
      permissions:
        id-token: write
        contents: read
  